import { config } from "dotenv";
config();
export const ConstApplicationId = "X-Parse-Application-Id";
export const ConstRestApiKey = "X-Parse-REST-API-Key";
export const ConstRevocableSession = "X-Parse-Revocable-Session";
export const ConstInstallationId = "X-Parse-Installation-Id";
export const ConstParseSessionToken = "X-Parse-Session-Token";
export const ApplicationId = process.env.PARSE_SERVER_APPLICATION_ID;
export const ParseServerUrl = process.env.PARSE_SERVER_URL;
export const ConstantParseServerLoginUrl = ParseServerUrl + "/login";
export const ConstantParseServerDeviceUrl = ParseServerUrl + "/classes/Devices";
export const ConstantParseServerUserUrl = ParseServerUrl + "/classes/Users";
